//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5448
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsUnitaires {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class PierreSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PierreSettings defaultInstance = ((PierreSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PierreSettings())));
        
        public static PierreSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
