//------------------------------------------------------------------------------
// <autogenerated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.832
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ScreenSaverPierre.Properties.Settings.get_Default():ScreenSaverPierre.Properties.Settings")]

namespace ScreenSaverPierre.Properties
{


    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        private static Settings defaultInstance = new Settings();

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string BackgroundImagePath
        {
            get
            {
                return ((string)(this["BackgroundImagePath"]));
            }
            set
            {
                this["BackgroundImagePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://go.microsoft.com/fwlink/?LinkId=49535")]
        public string RssFeedUri
        {
            get
            {
                return ((string)(this["RssFeedUri"]));
            }
            set
            {
                this["RssFeedUri"] = value;
            }
        }
    }
}
