//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5448
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsUnitaires.SWHelloWordPHP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:HelloYou", ConfigurationName="SWHelloWordPHP.HelloYouPort")]
    public interface HelloYouPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HelloYou:HelloYouPort:getHelloRequest", ReplyAction="urn:HelloYou:HelloYouPort:getHelloResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getHello(string prenom, string nom);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface HelloYouPortChannel : TestsUnitaires.SWHelloWordPHP.HelloYouPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class HelloYouPortClient : System.ServiceModel.ClientBase<TestsUnitaires.SWHelloWordPHP.HelloYouPort>, TestsUnitaires.SWHelloWordPHP.HelloYouPort {
        
        public HelloYouPortClient() {
        }
        
        public HelloYouPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloYouPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloYouPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloYouPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getHello(string prenom, string nom) {
            return base.Channel.getHello(prenom, nom);
        }
    }
}
