//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoCarWebApp.Model
{
    using System;
    
    [Flags]
    public enum EngineType : int
    {
        Essence = 0,
        Diesel = 1,
        GPL = 2
    }
}
