//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoCarWebApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfoCarEntityContainer : DbContext
    {
        public InfoCarEntityContainer()
            : base("name=InfoCarEntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> CarSet { get; set; }
        public virtual DbSet<Constructor> ConstructorSet { get; set; }
        public virtual DbSet<WearPart> WearPartSet { get; set; }
        public virtual DbSet<Fuel> FuelSet { get; set; }
        public virtual DbSet<Driver> DriverSet { get; set; }
        public virtual DbSet<DriverType> DriverTypeSet { get; set; }
    }
}
